package com.pockethub.ui.markdown

// GitHub emoji shortcode map (gemoji names) — the high-frequency subset found
// in the 550-README corpus survey. 27% of popular READMEs use :shortcode:
// syntax that GitHub renders as emoji; raw ":" names leak otherwise.

internal val EMOJI_SHORTCODES: Map<String, String> = mapOf(
    "tada" to "🎉", "rocket" to "🚀", "warning" to "⚠️", "white_check_mark" to "✅",
    "heavy_check_mark" to "✔️", "x" to "❌", "memo" to "📝", "bug" to "🐛",
    "fire" to "🔥", "star" to "⭐", "star2" to "🌟", "sparkles" to "✨",
    "books" to "📚", "book" to "📖", "package" to "📦", "wrench" to "🔧",
    "hammer" to "🔨", "gear" to "⚙️", "computer" to "💻", "laptop" to "💻",
    "iphone" to "📱", "smartphone" to "📱", "bulb" to "💡", "zap" to "⚡",
    "dart" to "🎯", "art" to "🎨", "page_facing_up" to "📄", "clipboard" to "📋",
    "pushpin" to "📌", "link" to "🔗", "globe_with_meridians" to "🌐",
    "earth_africa" to "🌍", "earth_americas" to "🌎", "earth_asia" to "🌏",
    "lock" to "🔒", "unlock" to "🔓", "key" to "🔑", "mag" to "🔍",
    "mag_right" to "🔎", "chart_with_upwards_trend" to "📈",
    "chart_with_downwards_trend" to "📉", "bar_chart" to "📊",
    "alarm_clock" to "⏰", "hourglass" to "⌛", "stop_sign" to "🛑",
    "construction" to "🚧", "truck" to "🚚", "car" to "🚗", "airplane" to "✈️",
    "house" to "🏠", "moneybag" to "💰", "dollar" to "💵", "credit_card" to "💳",
    "gift" to "🎁", "trophy" to "🏆", "medal" to "🏅", "green_heart" to "💚",
    "yellow_heart" to "💛", "blue_heart" to "💙", "purple_heart" to "💜",
    "heart" to "❤️", "broken_heart" to "💔", "thumbsup" to "👍",
    "+1" to "👍", "thumbsdown" to "👎", "-1" to "👎", "wave" to "👋",
    "clap" to "👏", "pray" to "🙏", "muscle" to "💪", "eyes" to "👀",
    "thinking" to "🤔", "smile" to "😄", "grin" to "😁", "joy" to "😂",
    "cry" to "😢", "sob" to "😭", "ghost" to "👻", "robot" to "🤖",
    "brain" to "🧠", "coffee" to "☕", "beer" to "🍺", "pizza" to "🍕",
    "snowflake" to "❄️", "sunny" to "☀️", "cloud" to "☁️", "rainbow" to "🌈",
    "seedling" to "🌱", "cactus" to "🌵", "palm_tree" to "🌴",
    "evergreen_tree" to "🌲", "fallen_leaf" to "🍂", "cat" to "🐱",
    "dog" to "🐶", "fox_face" to "🦊", "bear" to "🐻", "panda_face" to "🐼",
    "penguin" to "🐧", "whale" to "🐳", "fish" to "🐟", "octopus" to "🐙",
    "snake" to "🐍", "turtle" to "🐢", "bee" to "🐝", "butterfly" to "🦋",
    "alembic" to "⚗️", "telescope" to "🔭", "microscope" to "🔬",
    "test_tube" to "🧪", "pill" to "💊", "syringe" to "💉", "dna" to "🧬",
    "question" to "❓", "exclamation" to "❗", "grey_question" to "❔",
    "grey_exclamation" to "❕", "bangbang" to "‼️", "100" to "💯",
    "ok_hand" to "👌", "v" to "✌️", "crossed_fingers" to "🤞",
    "point_right" to "👉", "point_left" to "👈", "point_up" to "☝️",
    "point_down" to "👇", "raised_hands" to "🙌", "open_hands" to "👐",
    "handshake" to "🤝", "shrug" to "🤷", "facepalm" to "🤦",
    "soccer" to "⚽", "basketball" to "🏀", "baseball" to "⚾",
    "8ball" to "🎱", "game_die" to "🎲", "video_game" to "🎮",
    "musical_note" to "🎵", "notes" to "🎶", "microphone" to "🎤",
    "headphones" to "🎧", "camera" to "📷", "movie_camera" to "🎥",
    "tv" to "📺", "battery" to "🔋", "electric_plug" to "🔌",
    "floppy_disk" to "💾", "telephone" to "☎️", "satellite" to "📡",
    "bell" to "🔔", "no_bell" to "🔕", "bookmark" to "🔖",
    "bookmark_tabs" to "📑", "newspaper" to "📰", "email" to "✉️",
    "envelope" to "✉️", "inbox_tray" to "📥", "outbox_tray" to "📤",
    "pencil2" to "✏️", "pen" to "🖊️", "paintbrush" to "🖌️",
    "file_folder" to "📁", "open_file_folder" to "📂",
    "card_file_box" to "🗃️", "wastebasket" to "🗑️", "calendar" to "📅",
    "date" to "📅", "straight_ruler" to "📏", "triangular_ruler" to "📐",
    "scissors" to "✂️", "bomb" to "💣", "gun" to "🔫", "pill" to "💊",
    "beginner" to "🔰", "recycle" to "♻️", "sparkle" to "❇️",
    "arrow_up" to "⬆️", "arrow_down" to "⬇️", "arrow_left" to "⬅️",
    "arrow_right" to "➡️", "arrows_counterclockwise" to "🔄",
    "repeat" to "🔁", "fast_forward" to "⏩", "rewind" to "⏪",
    "arrow_up_small" to "🔼", "arrow_down_small" to "🔽",
    "information_source" to "ℹ️", "abc" to "🔤", "capital_abcd" to "🔠",
    "1234" to "🔢", "symbols" to "🔣", "capital_letters" to "🅰️",
    "a" to "🅰️", "ab" to "🆎", "b" to "🅱️", "cl" to "🆑", "cool" to "🆒",
    "free" to "🆓", "id" to "🆔", "new" to "🆕", "ng" to "🆖",
    "o" to "🅾️", "ok" to "🆗", "parking" to "🅿️", "sos" to "🆘",
    "up" to "🆙", "vs" to "🆚", "koko" to "🈁", "sa" to "🈂️",
    "u6708" to "🈷️", "u6e80" to "🈵", "checkered_flag" to "🏁",
    "triangular_flag_on_post" to "🚩", "crossed_flags" to "🎌",
    "white_flag" to "🏳️", "black_flag" to "🏴", "flower_playing_cards" to "🎴",
)
